### ISSUE TITLE
Linux CLI tools don't support --version or --help

### ISSUE THREAD

**Issue by edwinhayes** [OpenCyphal-Garage/libcyphal#136]
The Linux CLI tools don't support common arguments for getting help or version information, except for `uavcan_add_vcan`, which handles `--help` but not `--version`.

1. It would be helpful to be able to determine the version number of the library which is installed on a given machine.

2. I can't be the only person who wouldn't have expected that `uavcan_add_vcan --version` was actually going to create a new interface of that name!

**Comment by pavel-kirienko** [comment]
I would happily accept PRs fixing these shortcomings. Right now these are low-priority issues.

**Comment by edwinhayes** [comment]
Sure.  Am short staffed at the moment, but hopefully I'll be able to get someone to do this at some stage.
