### ISSUE TITLE
Usage info for uavcan_dynamic_node_id_server indicates cluster-size is optional.  It isn't.

### ISSUE THREAD

**Issue by edwinhayes** [OpenCyphal-Garage/libcyphal#137]
Running without the cluster size argument results in an error.  Should probably assume the cluster size is 1 if the argument is missing?

**Comment by pavel-kirienko** [comment]
The documentation is unclear, indeed. The cluster size parameter is required only if the server is launched for the first time, with the persistent storage being empty. Once the storage is initialized, the cluster size is stored in it, and the server can retrieve the value from there if not provided by the user.

**Comment by edwinhayes** [comment]
Ah, ok.  Thanks.
