### ISSUE TITLE
Allow sending and receiving CAN 2.0 messages when CAN-FD has been enabled.

### ISSUE THREAD

**Issue by thirtytwobits** [OpenCyphal-Garage/libcyphal#145]
(This task assumes #140 has been merged)

Allow for CAN 2.0 messages to be sent and received when CAN-FD support has been compiled into libuavcan.

This will require changes to the driver abstraction as some platforms will require changing the CAN peripheral to accept either FD or 2.0 frames.

Generally this feature is a placeholder needing lots of investigation, thought, and testing.

**Comment by pavel-kirienko** [comment]
> This will require changes to the driver abstraction as some platforms will require changing the CAN peripheral to accept either FD or 2.0 frames.

I think the choice between CAN2.0 and CAN FD should be dictated by the driver. We could add a method to `ICanDriver` that returns the MTU in bytes. Platforms that support only CAN2.0 would always return 8; platforms that support both would return either 8 (if they desire to use CAN2.0 only) or some other value up to 64 (smaller values may be preferred for higher preemption granularity). Upper layers of the library do not really care about the transport per se, they only care about MTU.
