### ISSUE TITLE
NuttX testing target for v0

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal-Garage/libcyphal#153]
@LorenzMeier @davids5 @dagar Is it possible to get some help with this?

Context: https://github.com/UAVCAN/libuavcan/pull/140#discussion_r202593588

**Comment by dagar** [comment]
What do you mean exactly? If it's actual automated testing with real hardware I'd be interested in helping, but ideally it would overlap with something that can also run PX4.

**Comment by davids5** [comment]
@pavel-kirienko - While H7 is now on master in NuttX. Unfortunately Greg removed libuavcan support after it failed to build. PX4 is still on an older branch and the upgrade will require all the board configs to be revetted.   So there is no quick path to get a test fixture up and running here.

**Comment by pavel-kirienko** [comment]
We don't really need a built-in libuavcan support in NuttX. What we need is a simple application that instantiates a UAVCAN node using libuavcan, broadcasts some simple messages and invokes/serves some services. The objective is to ensure that the library compiles against relatively modern versions of NuttX. Unless they managed to fix their C++ standard library, Libuavcan is going to require certain NuttX-specific hacks to make it work there (it is also the reason why it broke after the last upgrade I suppose). Being able to test that with real hardware in an automated fashion is a huge plus, but not strictly required at the moment. The test application can also be probably based on PX4 if that helps.
