### ISSUE TITLE
Allow network buffers to work directly with peripheral memory

### ISSUE THREAD

**Issue by thirtytwobits** [OpenCyphal-Garage/libcyphal#225]
![image](https://user-images.githubusercontent.com/19180861/58359312-b1097980-7e37-11e9-8717-a5f8cbb6a79c.png)

The above diagram shows how memory is copied from peripheral memory into system memory before it is again copied by the transport layer into the final message data passed to applications. It should be possible to allow a platform to expose the peripheral memory directly to the transport layer using the media layer as an abstract memory view. This will require an abstract means for safely sharing this memory so there's some careful design that has to occur first.

**Comment by pavel-kirienko** [comment]
Superseded by https://github.com/OpenCyphal-Garage/libcyphal/issues/225

Implementation in https://github.com/OpenCyphal-Garage/libcyphal/pull/407
