### ISSUE TITLE
Port transport layer to v1

### ISSUE THREAD

**Issue by thirtytwobits** [OpenCyphal-Garage/libcyphal#235]
This is a placeholder. Hopefully I can break this down into several/many tasks before starting on the Alpha milestone.

**Comment by pavel-kirienko** [comment]
Sub-tasks:
https://github.com/UAVCAN/libuavcan/issues/181
https://github.com/UAVCAN/libuavcan/issues/185
https://github.com/UAVCAN/libuavcan/issues/186
