### ISSUE TITLE
Allow for > 1 byte alignment in media layer frames

### ISSUE THREAD

**Issue by thirtytwobits** [OpenCyphal-Garage/libcyphal#309]
Currently we define data buffers in the media layer as byte arrays. Some systems may have alignment requirements that make this configuration inefficient. We should modify CAN frame templates to allow other alignments.

This was first detected as a consideration when building a media layer on top of the NXP FlexCAN IP. This peripheral uses 4-byte aligned data buffers.

**Comment by pavel-kirienko** [comment]
This is no longer in scope for libcyphal; if still necessary, it will be addressed in libcanard.
