### ISSUE TITLE
Design of transport layer

### ISSUE THREAD

**Issue by thirtytwobits** [OpenCyphal-Garage/libcyphal#317]
1. No dynamic memory except for I/O buffers
2. Must be fully functional on top of media layer (i.e. shall not need application layer to send and receive transfers.
3. Use pyuavcan as inspireation
4. See CONTRIBUTING.md for the overall design discussion for this library

Output should include definition of API for transport layer and supporting documentation.

**Comment by coderkalyan** [comment]
Hey all. Apologies but due to increased academic commitments, I won't be able to complete this. If anything changes later on, I will reassign myself to the issue, but for now I'm removing myself from it.

**Comment by pavel-kirienko** [comment]
Done in https://github.com/OpenCyphal-Garage/libcyphal/pull/333
