### ISSUE TITLE
Adjust the use of CETL_NODISCARD

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal-Garage/libcyphal#350]
- All non-void internal functions can (should) continue using CETL_NODISCARD.

- User-facing (API) functions can only use CETL_NODISCARD where unused return value may lead to a resource leak or some other disaster.

**Comment by serges147** [comment]
Closing as it was addressed by [PR 359](https://github.com/OpenCyphal-Garage/libcyphal/pull/359)
