### ISSUE TITLE
SingleThreadedExecutor: Consider removing pointer/int conversions

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal-Garage/libcyphal#373]
See https://github.com/OpenCyphal-Garage/libcyphal/pull/371#discussion_r1704756790_

One posisble way to approach this is to move the custom executor extension point into Callback::Any. This change affects only the SingleThreadedExecutor and everything below it, not the main codebase.

**Comment by pavel-kirienko** [comment]
This is not a high-priority issue because it affects only the specific implementation of one Executor policy. The core library is not affected. It is already possible to create an execution policy that does not need this.

**Comment by serges147** [comment]
Closing as fixed by PR #376
